/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "./src/pdfwriter/PDFWriter.hpp"
/* Header for class PdfWriter */

#ifndef _Included_PdfWriter
#define _Included_PdfWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PdfWriter
 * Method:    setWidthHeight
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_PdfWriter_setWidthHeight
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     PdfWriter
 * Method:    setFont
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_PdfWriter_setFont
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     PdfWriter
 * Method:    setContent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PdfWriter_setContent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PdfWriter
 * Method:    warpText
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_PdfWriter_warpText
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     PdfWriter
 * Method:    addToPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PdfWriter_addToPage
  (JNIEnv *, jobject);

/*
 * Class:     PdfWriter
 * Method:    addNewPage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PdfWriter_addNewPage
  (JNIEnv *, jobject);

/*
 * Class:     PdfWriter
 * Method:    writeToFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_PdfWriter_writeToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PdfWriter
 * Method:    setXY
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_PdfWriter_setXY
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
